### ISSUE TITLE
Show progress when searching online 

### ISSUE THREAD

**Issue by vlad-onis** [vlad-onis/twir_parser#21]

**Comment by TheRustyPickle** [comment]
Hello 👋! I'm not sure if you are taking contributions. I just found your repo and was looking at the issues. I was looking at the code though it seems the offline saving function `fetch_and_save_twir` isn't being used currently. However, I looked at the online search part and was able to create a simple loading bar. It looked something like this:

![Screenshot from 2023-07-06 06-04-55](https://github.com/vlad-onis/twir_parser/assets/35862475/529a2175-3c54-409d-8d76-844606bd9468)

Let me know what you think about it. Thanks!

**Comment by vlad-onis** [comment]
Hello!

Of course I take contributions, that is the whole point of it. I have so many ideas for this project, it is still in a very initial state.

The progress bar you just made is exactly what i have in mind. Could you please fork and open a MR. I'll gladly include it in the project.

Thanks for doing this, highly appreciated!

**Comment by vlad-onis** [comment]
@TheRustyPickle I assigned you to it. Thank you, again!

**Comment by TheRustyPickle** [comment]
I'll send a PR as soon as possible. Thank you!
